//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthKey
    {
        public int Id { get; set; }
        public string authstring { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
        public Nullable<int> id_owner { get; set; }
    
        public virtual user user { get; set; }
    }
}
