//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizCommon
{
    using System;
    using System.Collections.Generic;

    public partial class bizCard
    {
        public int Id { get; set; }
        public int id_owner { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string website { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string fax { get; set; }
        public string bizName { get; set; }
        public string adresa { get; set; }
        public string regCom { get; set; }
        public string codCIF { get; set; }
        public string Functie { get; set; }
        public string email { get; set; }
        public string imagePath { get; set; }

        public virtual user user { get; set; }
    }
}
